### PR TITLE
improving expire test coverage

### PR DESCRIPTION
**Pull request by pwmckenna**

### CODE REVIEW

**Comment by pwmckenna** [comment]
added a test for the existence/default value of the expire option, and also test the contents of the cache before the expiration.

**Comment by co2-git** [comment]
Awesome! Thanks @pwmckenna. I will push it to NPM this coming week! Cheers!

**Comment by pwmckenna** [comment]
no rush, just tests! i've got more coming. I was going to ask though, it would be nice to hook this up to travis to test pull requests (especially when the pull request changes tests), but I don't have access to this repo. Could I talk you into either adding me as a contributor, or login to travis and add this repo...provided there's interest. Thanks!

**Comment by co2-git** [comment]
Hey Patrick! I have no problem adding as a contributor and yes - it will be
sweet if this module could be hooked to travis!

**Comment by pwmckenna** [comment]
cool! I'll hook it up. I'll stay off of master though, and continue to just make pull requests. Now that I can make branches I can make multiple pull requests at once!

**Comment by pwmckenna** [comment]
ah, I can't actually hook up travis on your behalf. you'll need to go to https://travis-ci.org/profile/co2-git, sync, then toggle the check box for this repo.

**Comment by co2-git** [comment]
done :)

**Pull request merged**
