### PR TITLE
Statusexpire

### PR DESCRIPTION
**Pull request by pwmckenna**
adding support for expire values of objects, which are status code/expiration mappings (still supports just a number value).

ie,
```js
{
  '200': 1000,
  '4xx': 10,
  '403': 100000,
  'xxx': 100
}
```

### CODE REVIEW

**Comment by pwmckenna** [comment]
I think this could use some integration tests, where the route is created and used in a variety of ways, then the underlying redis entries are examined. Would that belong in test/route or in a new file? Not quite sure how to go about this.

**Comment by co2-git** [comment]
Hey @pwmckenna thanks for the PR! I'll update some stuff and let you know! Cheers!

**Comment by aamaliaa** [comment]
Hey guys, what's the status of this stuff? I would love to use it in my app but it appears it isn't in the newest release via npm (0.1.8). Thanks for this library, btw, super useful so far!

**Comment by co2-git** [comment]
Hey Amalia

Thanks for the <3! Yes, development is on and off on this project, so I
won't call it battle-tested mainly for that reason. Now seeing your poke,
I'll be spending some time on it this week, see if I can get something
sorted out. I will examine the tests to see how to integrate a better
reactive state. For me, the design is:
- if Redis server can not be accessed for any reason, then we should skip
  the cache altogether and go to the next middleware and do a dynamic
  rendering
- in such case, we should be emitting a disconnect event

What do you reckon?

Cheers

**Comment by co2-git** [comment]
Hey Patrick,

Sorry for the very late reply ;D Anyway, I'll probably write some Selenium
tests using webdriver.io. I don't know if that we will get our problem
solved but at least we'll have a better testing suite than before :)

Cheers,
F

**Pull request merged**
