### PR TITLE
Fixing cache expiration

### PR DESCRIPTION
**Pull request by rv-kip**
* Fixing cache expiration issue #15
* Unit test for expiration
* rename `cache` to `entry` to avoid confusion
* Adding TTL output on logging

### CODE REVIEW

**Comment by co2-git** [comment]
Thanks rv-kip :+1:

**Comment by rv-kip** [comment]
Was this meant to be closed instead of merged?

**Comment by rv-kip** [comment]
@co2-git, Is this not being merged for a reason? Or by mistake?

**Comment by co2-git** [comment]
By mistake! I thought I had merged :)

**Comment by rv-kip** [comment]
No problem! Thanks much!

**Pull request merged**
